### ISSUE TITLE
stage functions should not rely on the domain being a DomainBranch

### ISSUE THREAD

**Issue by pranavtbhat** [shashi/ComputeFramework.jl#21]
```julia
a = compute(Distribute(BlockPartition(10, 1), spzeros(10, 10)))
da = compute(a*a)
compute(map(x->1, da))
```

This throws an error:
```
ERROR: type DenseDomain has no field children
 in stage at /home/pranav/.julia/v0.5/ComputeFramework/src/map-reduce.jl:13
 [inlined code] from /home/pranav/.julia/v0.5/ComputeFramework/src/compute.jl:50
 in compute at /home/pranav/.julia/v0.5/ComputeFramework/src/compute.jl:51
 in eval at ./boot.jl:265
```
Other operations on `da` still work.

**Comment by pranavtbhat** [comment]
Fixed.

**Comment by shashi** [comment]
Huh? how?

This is still an issue, `stage` methods should not rely on the domain being a `DomainBranch`.

**Comment by shashi** [comment]
it's an easy fix. We need to have a `children` generic function as opposed to `d.children` which returns a 1-element domain in case of a non-DomainBranch object.
